name: NodeJS with ESLint and Webpack

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install
      run: |
        yarn install

    - name: Lint
      run: |
        yarn lint

    - name: Test
      run: |
        CI=true yarn test

    - name: Build
      run: |
        yarn build
